@ECHO OFF

::SET OPENOCD_PATH=%1
::SET OPENOCD_EXECUTABLE=%OPENOCD_PATH%\%3\
::SET MSYS_BIN=%4\bin
::SET MINGW_USR_BIN=%5\usr\bin
::SET MINGW_BIN=%5\bin
::SET MY_COMPILATOR=%2
::SET JAVA_HOME=%ProgramFiles%\Java\%6
::SET JRE_HOME=%ProgramFiles%\Java\%7
::SET BOOST_ROOT=%8
::SET QTDIR=C:\Qt\Qt5.10.1\5.10.1\msvc2017_64
::SET QWT_ROOT=C:\Qwt-6.1.4

IF [%1]==[] (
	GOTO WITHOUT_PYTHON
) ELSE (
	GOTO WITH_PYTHON
)

:WITH_PYTHON
SET MY_PYTHON=%~1
GOTO NEXT

:WITHOUT_PYTHON
SET MY_PYTHON=
ECHO "MY_PYTHON is empty"

:NEXT
IF [%2]==[] (
	GOTO WITHOUT_DXSDK
) ELSE (
	GOTO WITH_DXSDK
)

:WITH_DXSDK
SET DXSDK_DIR=%~2
ECHO "MY_PYTHON = %MY_PYTHON%"

:WITHOUT_DXSDK
IF DEFINED DXSDK_DIR (
	ECHO "DXSDK_DIR = %DXSDK_DIR%"
) ELSE (
	ECHO "DXSDK_DIR is empty"
)

SET MY_FAR="%PROGRAMFILES%\Far Manager"

SET PATH=%PATH%;%DXSDK_DIR%;%MY_PYTHON%;%MY_FAR%

ECHO "%PATH%"