@ECHO OFF

IF [%1]==[] (
	GOTO WITHOUT_PYTHON
) ELSE (
	GOTO WITH_PYTHON
)

:WITH_PYTHON
SET MY_PYTHON=%~1
GOTO NEXT

:WITHOUT_PYTHON
SET MY_PYTHON=
ECHO "MY_PYTHON is empty"

:NEXT
IF [%2]==[] (
	GOTO WITHOUT_DXSDK
) ELSE (
	GOTO WITH_DXSDK
)

:WITH_DXSDK
SET DXSDK_DIR=%~2
ECHO "MY_PYTHON = %MY_PYTHON%"

:WITHOUT_DXSDK
IF DEFINED DXSDK_DIR (
	ECHO "DXSDK_DIR = %DXSDK_DIR%"
) ELSE (
	ECHO "DXSDK_DIR is empty"
)

SET MY_FAR="%PROGRAMFILES%\Far Manager"

SET TOY_STORY3_BIN=W:\ToyStory3GamStar\CL329484\Bin

SET PATH=%PATH%;%DXSDK_DIR%;%MY_PYTHON%;%MY_FAR%;%TOY_STORY3_BIN%

ECHO "%PATH%"