@ECHO OFF

SET MY_PYTHON=%~1

SET MY_MSYS_DIR=%~2
SET MY_MSYS_BIN=%~3

SET MY_BAZELISK=%~4

SET MY_NUGET=%~5

SET MY_OPENCV=%~6

SET MY_FAR="%PROGRAMFILES%\Far Manager"

SET BAZEL_VS="%PROGRAMFILES(X86)%\Microsoft Visual Studio\2019\Community\"
SET BAZEL_VC="%PROGRAMFILES(X86)%\Microsoft Visual Studio\2019\Community\VC"
SET BAZEL_VC_FULL_VERSION="16.11.15"
SET BAZEL_WINSDK_FULL_VERSION="6.0A"

SET PATH=%PATH%;%MY_PYTHON%;%MY_MSYS_DIR%;%MY_MSYS_BIN%;%MY_BAZELISK%;%MY_NUGET%;%MY_OPENCV%;%MY_FAR%

ECHO "%PATH%"