@ECHO OFF

SET MY_PYTHON=%~1

SET MY_MSYS_DIR=%~2
SET MY_MSYS_BIN=%~3

SET MY_BAZELISK=%~4

SET MY_NUGET=%~5

SET MY_OPENCV=%~6

SET MY_FAR="%PROGRAMFILES%\Far Manager"

SET BAZEL_VS="%PROGRAMFILES(X86)%\Microsoft Visual Studio\2019\Community\"
SET BAZEL_VC="%PROGRAMFILES(X86)%\Microsoft Visual Studio\2019\Community\VC"
SET BAZEL_VC_FULL_VERSION=14.29.30133
SET BAZEL_WINSDK_FULL_VERSION=10.0.19041.0

SET JAVA_HOME=%~7
SET ANDROID_NDK_HOME=%~8
SET ANDROID_HOME=%~9

SET PATH=%JAVA_HOME%\bin;%ANDROID_HOME%;%ANDROID_NDK_HOME%;%PATH%;%MY_PYTHON%;%MY_MSYS_DIR%;%MY_MSYS_BIN%;%MY_BAZELISK%;%MY_NUGET%;%MY_OPENCV%;%MY_FAR%

ECHO "%PATH%"